import fs from "fs-extra";
import path from "path";

export interface ModuleFile {
  dest: string;
  content: string;
}

export interface Module {
  name: string;
  description: string;
  files: ModuleFile[];
}

export const AIOX_MODULES: Record<string, Module> = {
  types: {
    name: "Core Types",
    description: "Interfaces y tipos compartidos del sistema",
    files: [
      {
        dest: "src/core/types/index.ts",
        content: `/**
 * AIOX-Core v1.0 — Core Types & Interfaces
 * @generated by aiox-core CLI
 */

export type AgentStatus = 'ACTIVE' | 'PAUSED' | 'INACTIVE' | 'ERROR';

export interface IAgent {
  id: string;
  name: string;
  role: string;
  description?: string;
  status: AgentStatus;
  capabilities: string[];
  execute(task: string, context?: Record<string, any>): Promise<AgentExecutionResult>;
}

export interface AgentExecutionResult {
  agentId: string;
  agentName: string;
  success: boolean;
  output: string;
  data?: any;
  executionTimeMs: number;
  error?: string;
}

export type ModelProvider =
  | 'ollama' | 'deepseek' | 'qwen' | 'mistral'
  | 'openai' | 'claude' | 'gemini' | 'grok';

export type PrivacyLevel = 'HIGH' | 'MEDIUM' | 'LOW';
export type SpeedPreference = 'FAST' | 'BALANCED' | 'QUALITY';

export interface ModelRoutingCriteria {
  taskType: 'code' | 'research' | 'reasoning' | 'general' | 'creative' | 'automation';
  privacyRequired?: PrivacyLevel;
  speedPreference?: SpeedPreference;
  maxCostPer1kTokens?: number;
  qualityRequired?: 'STANDALONE' | 'HIGH' | 'PREMIUM';
  forceLocal?: boolean;
}

export interface ModelSelection {
  provider: ModelProvider;
  modelName: string;
  isLocal: boolean;
  estimatedLatencyMs: number;
  estimatedCostPer1kTokens: number;
  reason: string;
}

export interface ShortTermMemoryItem {
  id: string;
  sessionId: string;
  role: 'user' | 'agent' | 'system';
  content: string;
  timestamp: number;
  metadata?: Record<string, any>;
}

export interface LongTermMemoryItem {
  id: string;
  key: string;
  value: any;
  tags: string[];
  createdAt: number;
  updatedAt: number;
}

export interface KnowledgeDocument {
  id: string;
  title: string;
  category: string;
  content: string;
  tags: string[];
}

export interface VectorEmbedding {
  id: string;
  vector: number[];
  payload: Record<string, any>;
}

export type ToolType = 'N8N' | 'REST_API' | 'MCP' | 'WEBHOOK' | 'DATABASE' | 'AUTOMATION';

export interface ITool {
  id: string;
  name: string;
  description: string;
  type: ToolType;
  enabled: boolean;
  execute(input: Record<string, any>): Promise<ToolExecutionResult>;
}

export interface ToolExecutionResult {
  toolId: string;
  toolName: string;
  success: boolean;
  result: any;
  executionTimeMs: number;
  error?: string;
}

export type TaskStatus = 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED';

export interface TVSTask {
  id: string;
  title: string;
  description: string;
  requirements?: ModelRoutingCriteria;
  status: TaskStatus;
  subtasks?: TVSTask[];
  assignedAgentId?: string;
  result?: any;
  createdAt: number;
  completedAt?: number;
}

export interface OrchestrationReport {
  taskId: string;
  status: TaskStatus;
  subtaskResults: AgentExecutionResult[];
  overallOutput: string;
  durationMs: number;
}
`
      }
    ]
  },

  agentmanager: {
    name: "Agent Manager",
    description: "Registro dinámico de agentes para 200+",
    files: [
      {
        dest: "src/core/AgentManager.ts",
        content: `import { IAgent, AgentStatus, AgentExecutionResult } from "./types";

/**
 * AgentManager — AIOX-Core v1.0
 * Registro dinámico de agentes con indexado O(1). Soporte 200+ agentes.
 */
export class AgentManager {
  private agents: Map<string, IAgent> = new Map();
  private roleIndex: Map<string, Set<string>> = new Map();
  private capabilityIndex: Map<string, Set<string>> = new Map();

  public register(agent: IAgent): void {
    this.agents.set(agent.id, agent);
    this.index(agent);
    console.log(\`[AgentManager] ✓ Agente registrado: \${agent.name} (\${agent.role})\`);
  }

  public add(agent: any): void {
    const norm: IAgent = {
      id: agent.id || \`agent_\${Date.now()}\`,
      name: agent.name || 'GenericAgent',
      role: agent.role || 'General',
      status: 'ACTIVE',
      capabilities: agent.capabilities || [],
      execute: async (task: string): Promise<AgentExecutionResult> => {
        const start = Date.now();
        const output = typeof agent.execute === 'function' ? await agent.execute(task) : \`\${agent.name} procesó: \${task}\`;
        return { agentId: norm.id, agentName: norm.name, success: true, output: String(output), executionTimeMs: Date.now() - start };
      }
    };
    this.register(norm);
  }

  public activate(id: string): boolean { const a = this.agents.get(id); if (a) { a.status = 'ACTIVE'; return true; } return false; }
  public pause(id: string): boolean { const a = this.agents.get(id); if (a) { a.status = 'PAUSED'; return true; } return false; }
  public unregister(id: string): boolean {
    const a = this.agents.get(id);
    if (!a) return false;
    this.deindex(a);
    this.agents.delete(id);
    return true;
  }

  public getAgent(idOrName: string): IAgent | undefined {
    if (this.agents.has(idOrName)) return this.agents.get(idOrName);
    return Array.from(this.agents.values()).find(a => a.name === idOrName);
  }

  public list(status?: AgentStatus): IAgent[] {
    const all = Array.from(this.agents.values());
    return status ? all.filter(a => a.status === status) : all;
  }

  public getAgentsByRole(role: string): IAgent[] {
    const ids = this.roleIndex.get(role.toLowerCase());
    return ids ? Array.from(ids).map(id => this.agents.get(id)!).filter(Boolean) : [];
  }

  public getAgentsByCapability(cap: string): IAgent[] {
    const ids = this.capabilityIndex.get(cap.toLowerCase());
    return ids ? Array.from(ids).map(id => this.agents.get(id)!).filter(Boolean) : [];
  }

  public async run(idOrName: string, task: string, context?: Record<string, any>): Promise<AgentExecutionResult> {
    const agent = this.getAgent(idOrName);
    if (!agent) throw new Error(\`[AgentManager] Agente '\${idOrName}' no encontrado.\`);
    if (agent.status !== 'ACTIVE') throw new Error(\`[AgentManager] Agente '\${agent.name}' no está ACTIVE.\`);
    return agent.execute(task, context);
  }

  public getStats() {
    const s = { total: this.agents.size, active: 0, paused: 0, inactive: 0, error: 0 };
    for (const a of this.agents.values()) s[a.status.toLowerCase() as keyof typeof s]++;
    return s;
  }

  private index(agent: IAgent): void {
    const rk = agent.role.toLowerCase();
    if (!this.roleIndex.has(rk)) this.roleIndex.set(rk, new Set());
    this.roleIndex.get(rk)!.add(agent.id);
    for (const c of agent.capabilities) {
      const ck = c.toLowerCase();
      if (!this.capabilityIndex.has(ck)) this.capabilityIndex.set(ck, new Set());
      this.capabilityIndex.get(ck)!.add(agent.id);
    }
  }

  private deindex(agent: IAgent): void {
    this.roleIndex.get(agent.role.toLowerCase())?.delete(agent.id);
    for (const c of agent.capabilities) this.capabilityIndex.get(c.toLowerCase())?.delete(agent.id);
  }
}
`
      }
    ]
  },

  modelrouter: {
    name: "Model Router",
    description: "Enrutamiento multicriterio: Ollama, DeepSeek, Qwen, Mistral, OpenAI, Claude, Gemini, Grok",
    files: [
      {
        dest: "src/core/model-router/ModelRouter.ts",
        content: `import { ModelProvider, ModelRoutingCriteria, ModelSelection } from "../types";

export interface ModelProfile {
  provider: ModelProvider;
  modelName: string;
  isLocal: boolean;
  costPer1kTokens: number;
  latencyMs: number;
  qualityScore: number;
  supportedTasks: string[];
}

/**
 * ModelRouter — AIOX-Core v1.0
 * Enrutamiento inteligente: Local (Ollama/DeepSeek/Qwen/Mistral) + Cloud (OpenAI/Claude/Gemini/Grok)
 */
export class ModelRouter {
  private registry: Map<ModelProvider, ModelProfile> = new Map();

  constructor() {
    [
      { provider: 'ollama' as ModelProvider, modelName: 'llama3:8b', isLocal: true, costPer1kTokens: 0, latencyMs: 150, qualityScore: 78, supportedTasks: ['general', 'creative', 'automation'] },
      { provider: 'deepseek' as ModelProvider, modelName: 'deepseek-r1:local', isLocal: true, costPer1kTokens: 0, latencyMs: 300, qualityScore: 92, supportedTasks: ['code', 'reasoning', 'research'] },
      { provider: 'qwen' as ModelProvider, modelName: 'qwen2.5-coder:local', isLocal: true, costPer1kTokens: 0, latencyMs: 200, qualityScore: 88, supportedTasks: ['code', 'automation'] },
      { provider: 'mistral' as ModelProvider, modelName: 'mistral-nemo:local', isLocal: true, costPer1kTokens: 0, latencyMs: 180, qualityScore: 82, supportedTasks: ['general', 'reasoning'] },
      { provider: 'claude' as ModelProvider, modelName: 'claude-3-7-sonnet', isLocal: false, costPer1kTokens: 0.003, latencyMs: 600, qualityScore: 98, supportedTasks: ['code', 'reasoning', 'creative', 'research'] },
      { provider: 'openai' as ModelProvider, modelName: 'gpt-4o', isLocal: false, costPer1kTokens: 0.0025, latencyMs: 500, qualityScore: 95, supportedTasks: ['general', 'code', 'automation', 'reasoning'] },
      { provider: 'gemini' as ModelProvider, modelName: 'gemini-2.0-flash', isLocal: false, costPer1kTokens: 0.0001, latencyMs: 250, qualityScore: 90, supportedTasks: ['research', 'general', 'automation'] },
      { provider: 'grok' as ModelProvider, modelName: 'grok-3', isLocal: false, costPer1kTokens: 0.002, latencyMs: 400, qualityScore: 91, supportedTasks: ['research', 'creative', 'reasoning'] },
    ].forEach(m => this.registry.set(m.provider, m));
  }

  public route(criteria: ModelRoutingCriteria): ModelSelection {
    let candidates = Array.from(this.registry.values());
    if (criteria.privacyRequired === 'HIGH' || criteria.forceLocal) candidates = candidates.filter(m => m.isLocal);
    if (!candidates.length) candidates = Array.from(this.registry.values()).filter(m => m.isLocal);
    const taskMatch = candidates.filter(m => m.supportedTasks.includes(criteria.taskType));
    if (taskMatch.length) candidates = taskMatch;
    let chosen = candidates[0];
    if (criteria.speedPreference === 'FAST') chosen = candidates.sort((a, b) => a.latencyMs - b.latencyMs)[0];
    else if (criteria.qualityRequired === 'PREMIUM') chosen = candidates.sort((a, b) => b.qualityScore - a.qualityScore)[0];
    else chosen = candidates.sort((a, b) => (b.qualityScore / (b.latencyMs + 100)) - (a.qualityScore / (a.latencyMs + 100)))[0];
    return { provider: chosen.provider, modelName: chosen.modelName, isLocal: chosen.isLocal, estimatedLatencyMs: chosen.latencyMs, estimatedCostPer1kTokens: chosen.costPer1kTokens, reason: \`Seleccionado \${chosen.provider} para '\${criteria.taskType}'\` };
  }

  public select(task: string): string {
    const t = task.toLowerCase();
    const taskType: ModelRoutingCriteria['taskType'] = t.includes('codigo') || t.includes('code') ? 'code' : t.includes('investigar') ? 'research' : 'general';
    return this.route({ taskType, privacyRequired: t.includes('local') ? 'HIGH' : 'LOW' }).provider;
  }

  public execute(task: string): string {
    const p = this.select(task);
    console.log(\`[ModelRouter] Modelo seleccionado: \${p}\`);
    return p;
  }
}
`
      }
    ]
  },

  orchestrator: {
    name: "TVS Orchestrator",
    description: "Motor de coordinación principal, división y delegación de tareas",
    files: [
      {
        dest: "src/core/orchestrator/Orchestrator.ts",
        content: `import { AgentManager } from "../AgentManager";
import { ModelRouter } from "../model-router/ModelRouter";
import { MemoryEngine } from "../memory/MemoryEngine";
import { ToolManager } from "../tools/ToolManager";
import { OrchestrationReport, AgentExecutionResult, ModelRoutingCriteria } from "../types";

/**
 * TVSOrchestrator — AIOX-Core v1.0
 * Motor principal: recibe tareas, descompone, delega a agentes y sintetiza.
 */
export class TVSOrchestrator {
  public agentManager: AgentManager;
  public modelRouter: ModelRouter;
  public memoryEngine: MemoryEngine;
  public toolManager: ToolManager;
  public agents: any[] = [];

  constructor(agentManager?: AgentManager, modelRouter?: ModelRouter, memoryEngine?: MemoryEngine, toolManager?: ToolManager) {
    this.agentManager = agentManager || new AgentManager();
    this.modelRouter = modelRouter || new ModelRouter();
    this.memoryEngine = memoryEngine || new MemoryEngine();
    this.toolManager = toolManager || new ToolManager();
  }

  public register(agent: any): void { this.agents.push(agent); this.agentManager.add(agent); }
  public add(agent: any): void { this.register(agent); }

  public async orchestrate(title: string, description: string, criteria?: ModelRoutingCriteria): Promise<OrchestrationReport> {
    const start = Date.now();
    const taskId = \`task_\${Date.now()}_\${Math.random().toString(36).slice(2, 7)}\`;
    console.log(\`\\n[TVSOrchestrator] Iniciando: "\${title}" (ID: \${taskId})\`);
    this.memoryEngine.addShortTerm(taskId, 'user', description, { title });
    const routing = this.modelRouter.route(criteria || { taskType: this.inferType(title + description) });
    console.log(\`[TVSOrchestrator] Modelo: \${routing.provider}\`);
    const subtasks = [
      { id: 'sub_1', title: 'Análisis', description: \`Analizar: \${title}\`, requiredRole: 'Architect' },
      { id: 'sub_2', title: 'Desarrollo', description: \`Implementar: \${title}\`, requiredRole: 'Developer' },
      { id: 'sub_3', title: 'Seguridad', description: \`Auditar: \${title}\`, requiredRole: 'Security' },
    ];
    const results: AgentExecutionResult[] = [];
    for (const sub of subtasks) {
      const agents = this.agentManager.getAgentsByRole(sub.requiredRole);
      const agent = agents.find(a => a.status === 'ACTIVE') || this.agentManager.list('ACTIVE')[0] || this.agentManager.list()[0];
      if (agent) {
        const res = await this.agentManager.run(agent.id, sub.description);
        results.push(res);
      }
    }
    const dur = Date.now() - start;
    this.memoryEngine.setLongTerm(taskId, { title, durationMs: dur }, ['task_history']);
    console.log(\`[TVSOrchestrator] Completado en \${dur}ms.\`);
    return { taskId, status: results.every(r => r.success) ? 'COMPLETED' : 'FAILED', subtaskResults: results, overallOutput: results.map(r => \`[\${r.agentName}]: \${r.output}\`).join('\\n'), durationMs: dur };
  }

  public async execute(task: string): Promise<void> { await this.run(task); }
  public async run(task: string): Promise<void> {
    for (const a of this.agents) {
      if (typeof a.run === 'function') a.run(task);
      if (typeof a.execute === 'function') await a.execute(task);
    }
  }

  private inferType(text: string): ModelRoutingCriteria['taskType'] {
    const t = text.toLowerCase();
    if (t.includes('codigo') || t.includes('code')) return 'code';
    if (t.includes('investigar')) return 'research';
    if (t.includes('arquitectura')) return 'reasoning';
    if (t.includes('automatizar') || t.includes('n8n')) return 'automation';
    return 'general';
  }
}

export class Orchestrator extends TVSOrchestrator {}
`
      }
    ]
  },

  memory: {
    name: "Memory Engine",
    description: "Short Term, Long Term, Knowledge Base y Qdrant Vector Store",
    files: [
      {
        dest: "src/core/memory/MemoryEngine.ts",
        content: `import fs from "fs-extra";
import path from "path";
import { ShortTermMemoryItem, LongTermMemoryItem, KnowledgeDocument, VectorEmbedding } from "../types";

/**
 * MemoryEngine — AIOX-Core v1.0
 * STM + LTM (JSON persistido) + Knowledge Base + Vector Memory (Qdrant-ready)
 */
export class MemoryEngine {
  private stm: Map<string, ShortTermMemoryItem[]> = new Map();
  private ltm: Map<string, LongTermMemoryItem> = new Map();
  private kb: Map<string, KnowledgeDocument> = new Map();
  private vectors: Map<string, VectorEmbedding> = new Map();
  private storagePath: string;

  constructor(storageDir?: string) {
    this.storagePath = storageDir || path.join(process.cwd(), 'database', 'memory');
    fs.ensureDirSync(this.storagePath);
    this.loadLTM();
  }

  addShortTerm(sessionId: string, role: 'user'|'agent'|'system', content: string, metadata?: Record<string, any>): ShortTermMemoryItem {
    const item: ShortTermMemoryItem = { id: \`stm_\${Date.now()}\`, sessionId, role, content, timestamp: Date.now(), metadata };
    if (!this.stm.has(sessionId)) this.stm.set(sessionId, []);
    this.stm.get(sessionId)!.push(item);
    return item;
  }
  getShortTerm(sessionId: string, limit = 20) { return (this.stm.get(sessionId) || []).slice(-limit); }
  clearShortTerm(sessionId: string) { this.stm.delete(sessionId); }

  setLongTerm(key: string, value: any, tags: string[] = []): LongTermMemoryItem {
    const now = Date.now();
    const ex = this.ltm.get(key);
    const item: LongTermMemoryItem = { id: ex?.id || \`ltm_\${now}\`, key, value, tags, createdAt: ex?.createdAt || now, updatedAt: now };
    this.ltm.set(key, item);
    this.saveLTM();
    return item;
  }
  getLongTerm(key: string) { return this.ltm.get(key)?.value; }
  searchLongTermByTag(tag: string) { return Array.from(this.ltm.values()).filter(i => i.tags.includes(tag)); }

  addKnowledge(title: string, category: string, content: string, tags: string[] = []): KnowledgeDocument {
    const doc: KnowledgeDocument = { id: \`kb_\${Date.now()}\`, title, category, content, tags };
    this.kb.set(doc.id, doc);
    return doc;
  }
  searchKnowledge(query: string) {
    const q = query.toLowerCase();
    return Array.from(this.kb.values()).filter(d => d.title.toLowerCase().includes(q) || d.content.toLowerCase().includes(q));
  }

  async storeVector(vector: number[], payload: Record<string, any>): Promise<string> {
    const id = \`vec_\${Date.now()}_\${Math.random().toString(36).slice(2, 7)}\`;
    this.vectors.set(id, { id, vector, payload });
    return id;
  }
  async queryVector(queryVector: number[], topK = 5): Promise<VectorEmbedding[]> {
    const cos = (v1: number[], v2: number[]) => { let d = 0, n1 = 0, n2 = 0; for (let i = 0; i < v1.length; i++) { d += v1[i] * (v2[i] || 0); n1 += v1[i] ** 2; n2 += (v2[i] || 0) ** 2; } return d / (Math.sqrt(n1) * Math.sqrt(n2) || 1); };
    return Array.from(this.vectors.values()).map(v => ({ v, s: cos(queryVector, v.vector) })).sort((a, b) => b.s - a.s).slice(0, topK).map(x => x.v);
  }

  private saveLTM() {
    try { fs.writeJsonSync(path.join(this.storagePath, 'ltm.json'), Array.from(this.ltm.values()), { spaces: 2 }); } catch {}
  }
  private loadLTM() {
    try { const f = path.join(this.storagePath, 'ltm.json'); if (fs.existsSync(f)) { (fs.readJsonSync(f) as LongTermMemoryItem[]).forEach(i => this.ltm.set(i.key, i)); } } catch {}
  }
}
`
      }
    ]
  },

  tools: {
    name: "Tool Manager",
    description: "Gestor extensible: n8n, REST API, MCP, Webhooks, Bases de Datos, Automatizaciones",
    files: [
      {
        dest: "src/core/tools/ToolManager.ts",
        content: `import { ITool, ToolType, ToolExecutionResult } from "../types";

/**
 * ToolManager — AIOX-Core v1.0
 * Registro y ejecución de herramientas: n8n, REST, MCP, Webhooks, DB, Automatizaciones.
 */
export class ToolManager {
  private tools: Map<string, ITool> = new Map();

  registerTool(tool: ITool): void { this.tools.set(tool.id, tool); console.log(\`[ToolManager] ✓ Herramienta: '\${tool.name}' (\${tool.type})\`); }
  getTool(id: string) { return this.tools.get(id); }
  listTools(type?: ToolType) { const all = Array.from(this.tools.values()); return type ? all.filter(t => t.type === type) : all; }
  setEnabled(id: string, enabled: boolean): boolean { const t = this.tools.get(id); if (t) { t.enabled = enabled; return true; } return false; }

  async executeTool(id: string, input: Record<string, any>): Promise<ToolExecutionResult> {
    const tool = this.tools.get(id);
    if (!tool) return { toolId: id, toolName: 'Unknown', success: false, result: null, executionTimeMs: 0, error: \`Herramienta '\${id}' no encontrada.\` };
    if (!tool.enabled) return { toolId: id, toolName: tool.name, success: false, result: null, executionTimeMs: 0, error: 'Herramienta desactivada.' };
    const start = Date.now();
    try {
      const res = await tool.execute(input);
      return { toolId: id, toolName: tool.name, success: true, result: res.result ?? res, executionTimeMs: Date.now() - start };
    } catch (e: any) {
      return { toolId: id, toolName: tool.name, success: false, result: null, executionTimeMs: Date.now() - start, error: e.message };
    }
  }

  createQuickTool(id: string, name: string, type: ToolType, description: string, handler: (input: Record<string, any>) => Promise<any>): ITool {
    const tool: ITool = { id, name, description, type, enabled: true, execute: async (input) => { const s = Date.now(); const r = await handler(input); return { toolId: id, toolName: name, success: true, result: r, executionTimeMs: Date.now() - s }; } };
    this.registerTool(tool);
    return tool;
  }
}
`
      }
    ]
  },

  squads: {
    name: "Squad Manager",
    description: "Squads con líderes Pedro y Trinnity, permisos jerárquicos",
    files: [
      {
        dest: "src/core/squads/SquadManager.ts",
        content: `import { IAgent, AgentExecutionResult } from "../types";

export type Permission = 'EXECUTE_TOOLS' | 'ACCESS_MEMORY' | 'ROUTE_MODELS' | 'MANAGE_AGENTS' | 'SYSTEM_ADMIN';

export interface Squad { id: string; name: string; leader: IAgent; members: IAgent[]; permissions: Permission[]; description: string; }

/**
 * SquadManager — AIOX-Core v1.0
 * Agentes líderes Pedro y Trinnity. Sistema de permisos por equipo.
 */
export class SquadManager {
  private squads: Map<string, Squad> = new Map();
  public leaderPedro: IAgent;
  public leaderTrinnity: IAgent;

  constructor() {
    this.leaderPedro = {
      id: 'agent_pedro_leader', name: 'Pedro', role: 'CEO & Strategic Leader', status: 'ACTIVE',
      description: 'Líder de visión estratégica, gobernanza y toma de decisiones globales.',
      capabilities: ['strategic_planning', 'squad_governance', 'decision_making'],
      execute: async (task: string): Promise<AgentExecutionResult> => ({ agentId: 'agent_pedro_leader', agentName: 'Pedro (CEO)', success: true, output: \`[Pedro] Estrategia aprobada para: '\${task}'\`, executionTimeMs: 25 })
    };
    this.leaderTrinnity = {
      id: 'agent_trinnity_leader', name: 'Trinnity', role: 'Chief Architect & Technical Leader', status: 'ACTIVE',
      description: 'Líder de arquitectura, orquestación de modelos y super-aprendizaje.',
      capabilities: ['system_architecture', 'model_routing', 'vector_learning'],
      execute: async (task: string): Promise<AgentExecutionResult> => ({ agentId: 'agent_trinnity_leader', agentName: 'Trinnity (Architect)', success: true, output: \`[Trinnity] Arquitectura diseñada para: '\${task}'\`, executionTimeMs: 30 })
    };
    this.createSquad({ id: 'squad_executive', name: 'Executive & Governance Squad', leader: this.leaderPedro, members: [this.leaderPedro], permissions: ['EXECUTE_TOOLS', 'ACCESS_MEMORY', 'ROUTE_MODELS', 'MANAGE_AGENTS', 'SYSTEM_ADMIN'], description: 'Decisiones de alto nivel.' });
    this.createSquad({ id: 'squad_architecture', name: 'Core Architecture & Engineering Squad', leader: this.leaderTrinnity, members: [this.leaderTrinnity], permissions: ['EXECUTE_TOOLS', 'ACCESS_MEMORY', 'ROUTE_MODELS'], description: 'Desarrollo técnico y ruteo de modelos.' });
  }

  createSquad(squad: Squad): void { this.squads.set(squad.id, squad); console.log(\`[SquadManager] Squad creado: '\${squad.name}' (Líder: \${squad.leader.name})\`); }
  addMember(squadId: string, agent: IAgent): boolean { const s = this.squads.get(squadId); if (!s) return false; if (!s.members.some(m => m.id === agent.id)) s.members.push(agent); return true; }
  hasPermission(agentId: string, perm: Permission): boolean { for (const s of this.squads.values()) { if ((s.members.some(m => m.id === agentId) || s.leader.id === agentId) && s.permissions.includes(perm)) return true; } return false; }
  addMemberToSquad(squadId: string, agent: IAgent): boolean { return this.addMember(squadId, agent); }
  getSquads(): Squad[] { return Array.from(this.squads.values()); }
}
`
      }
    ]
  },

  learning: {
    name: "Auto Learning Engine",
    description: "Ciclo de aprendizaje continuo cada 15 minutos para Pedro y Trinnity",
    files: [
      {
        dest: "src/core/learning/AutoLearningEngine.ts",
        content: `import cron from "node-cron";
import { MemoryEngine } from "../memory/MemoryEngine";
import { SquadManager } from "../squads/SquadManager";

/**
 * AutoLearningEngine — AIOX-Core v1.0
 * Ciclo de auto-aprendizaje cada 15 minutos. Nutre el cerebro de Pedro y Trinnity con la experiencia AIOX.
 */
export class AutoLearningEngine {
  private memory: MemoryEngine;
  private squads: SquadManager;
  private job: cron.ScheduledTask | null = null;
  private cycle = 0;

  constructor(memory: MemoryEngine, squads: SquadManager) {
    this.memory = memory;
    this.squads = squads;
  }

  startLearningCycle(): void {
    console.log('[AutoLearningEngine] ⏱ Ciclo de aprendizaje iniciado (cada 15 min)...');
    this.executeLearningCycle();
    this.job = cron.schedule('*/15 * * * *', () => this.executeLearningCycle());
  }

  stopLearningCycle(): void { if (this.job) { this.job.stop(); console.log('[AutoLearningEngine] Ciclo detenido.'); } }

  async executeLearningCycle(): Promise<void> {
    this.cycle++;
    const ts = Date.now();
    const insight = \`Aprendizaje AIOX #\${this.cycle}: Optimización de patrones, ruteo y gobernanza de squads.\`;
    this.memory.addKnowledge(\`AIOX Learning #\${this.cycle}\`, 'CONTINUOUS_LEARNING', insight, ['auto_learning', 'pedro', 'trinnity', 'aiox']);
    const vec = Array.from({ length: 1536 }, () => (Math.random() - 0.5) * 2);
    await this.memory.storeVector(vec, { cycle: this.cycle, insight, leaders: ['Pedro', 'Trinnity'], timestamp: ts });
    this.memory.setLongTerm('pedro_brain_state', { cycle: this.cycle, knowledgeLevel: 50 + this.cycle * 0.1, status: 'OPTIMIZED', updatedAt: ts }, ['pedro', 'brain']);
    this.memory.setLongTerm('trinnity_brain_state', { cycle: this.cycle, knowledgeLevel: 50 + this.cycle * 0.1, status: 'OPTIMIZED', updatedAt: ts }, ['trinnity', 'brain']);
    console.log(\`[AutoLearningEngine] ✓ Ciclo #\${this.cycle} completado — Pedro & Trinnity actualizados.\`);
  }
}
`
      }
    ]
  }
};

export function getModuleFiles(moduleKeys: string[]): ModuleFile[] {
  const files: ModuleFile[] = [];
  // Always include types
  if (!moduleKeys.includes('types')) {
    files.push(...(AIOX_MODULES['types']?.files || []));
  }
  for (const key of moduleKeys) {
    const mod = AIOX_MODULES[key];
    if (mod) files.push(...mod.files);
  }
  return files;
}

export function writeModuleFiles(targetDir: string, files: ModuleFile[]): void {
  for (const file of files) {
    const fullPath = path.join(targetDir, file.dest);
    fs.ensureDirSync(path.dirname(fullPath));
    fs.writeFileSync(fullPath, file.content, 'utf-8');
  }
}
